# Generated by Django 2.1.5 on 2019-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
