# Generated by Django 2.1.5 on 2019-04-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0002_auto_20190321_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgurl',
            field=models.URLField(max_length=2000),
        ),
    ]
