# Generated by Django 2.1.5 on 2019-04-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0003_auto_20190412_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgurl',
            field=models.URLField(max_length=3000),
        ),
    ]
